### ISSUE TITLE
Increase size of the webtool's header

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltWebTool#119]
Dear @maurolepore, 

Can we please make the headers of the webtool bigger. I also had a look here: 

> See if what you want can be changed by adjusting one of these arguments:
> [https://rstudio.github.io/bslib/reference/bs_theme.html#arguments](https://www.google.com/url?q=https://rstudio.github.io/bslib/reference/bs_theme.html%23arguments&sa=D&source=docs&ust=1720434398938802&usg=AOvVaw0rnpIi9W0ZNoGuOA5EI3OQ)

Apparently there is an argument which is called `heading_font`. I however was not able to customise this in the live-themer. I remember that there where this option but when I changed it, for any reasons it didn't show up. So could you experiment a bit and let me know which number you gave to the argument and I can then see if we still need to adjust it or not. 

Thanks a lot!
Best
Anne

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer, I'll follow up.

For now here's what I see in the [docs](https://rstudio.github.io/bslib/reference/bs_theme.html#arguments):

![image](https://github.com/2DegreesInvesting/tiltWebTool/assets/5856545/11c0ff7f-affa-43d7-b36e-6649212001f5)

* `header_font` seems to control the font faze not the font size.
* `font_scale` seems to control the font size but globally. This should be easy but it's not specifically for the header.

I would avoid or postpone tweaking specific components of the theme because of two reasons:
1. The theme-proportions were set by expert web designers. Changing them might not be a good idea.
2. It seems more complicated than just passing a different value. For a web-developer with experience in CSS it should be easy but for me it may take quite some time. If that's what we want, then I see some [examples of low-level theming customizations](https://rstudio.github.io/bslib/reference/bs_bundle.html#ref-examples) showing how to change CSS properties, e.g.:

```
  "font-size-base" = "1.4rem",
```

**Comment by maurolepore** [comment]
* Closing in favor of #182
