### ISSUE TITLE
Opening the webtool sometimes create a weird page

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltWebTool#131]
Hi @maurolepore 
this happened today for the second time that when I am loading the website, I receive this 
<img width="935" alt="image" src="https://github.com/user-attachments/assets/a253a28c-5aed-4440-8db9-6661b434807e">
When I again upload the page it looks normal. 
Best
Anne

**Comment by maurolepore** [comment]
Thanks Anne. Yeah, I've seen this a few times too. It seems to be a problem in the way HTML is interpreted by the web browser. 

I also experienced that refreshing solves the problem, so I don't see how changing the code would have an any effect. I'm happy to research it if we make it a priority. But seems like it might be a great sucker for time we don't have. So not sure if/when it'll be worth to get to the bottom of this :-(

**Comment by AnneSchoenauer** [comment]
Hi @maurolepore - understood! Let’s leave it open for now and we see in future how we can squeeze it in!

**Comment by maurolepore** [comment]
After a bit of experimentation I can reproduce the problem. Apps looks odd on a "cold start" but refreshing the browser fixes the problem. 

A cold start happens when nobody has been using the app for more than the time [we configure as `timeout`](https://github.com/2DegreesInvesting/tiltWebTool/issues/229) (e.g. 10'). After timeout the computer that serves the app shuts down to save costs and energy.

> A "cold start" in Google Cloud Run occurs when a request must wait for a new container instance to process it. This can happen when scaling from zero.

We can avoid cold starts by always leaving 1 computer running but this will waste energy and money. We may continue to investigate the ultimate cause but it seems like a rabbit whole that is not worth the effort, since refreshing the browser seems intuitive and easy.

## Cold start

![Image](https://github.com/user-attachments/assets/3dcb5431-d31e-4d89-9872-7787ebcc0fed)

## After refresh

![Image](https://github.com/user-attachments/assets/3834c79a-9069-4ffd-a452-c23b7dbb395b)
