### ISSUE TITLE
Add "climate action guide" section, next to "methodology"

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltWebTool#196]
Dear @maurolepore, 

Could you please add a Tab which is called "Climate Action Guide". The body of the text should be: 

"A first version of our climate action guide that collects revenue, and climate action information in a standardized way from the SME and can be used to (i) enhance the automated output data quality as well as (ii) engage with the SME clients and offer tailored sustainability improvement loans. The idea is that SMEs only need 15 minutes to fill in the questionnaire with "yes" and "no" questions. We already tested the Climate Action Guide with 3 SMEs. Results can be found here[URL will follow]. 

Please also upload this XLS sheet so that people can download the XLS sheet from the website. Please note that it would be good to upload the whole sheet as it is locked. If we upload it on Google XLS it can be that the cells are unlocked again. Is there a way of uploading documents that people can then download? Or shall we dive into solutions to look the XLS sheets also on Google Form? @Tilmon 

[Climate_Action_Questionnaire_tilt_user_platform.xlsx](https://github.com/user-attachments/files/16625497/Climate_Action_Questionnaire_tilt_user_platform.xlsx)

```
https://github.com/user-attachments/files/16625497/Climate_Action_Questionnaire_tilt_user_platform.xlsx
```

**Comment by maurolepore** [comment]
@AnneSchoenauer, 

Are you asking to allow users to download that .xlxs sheet when the click on "Results can be found here"?

**Comment by kalashsinghal** [comment]
New file for climate action guide ([slack comment](https://2investinginitiative.slack.com/archives/C04Q36P543D/p1725629109847359?thread_ts=1725624874.050209&cid=C04Q36P543D)):

[Climate_Action_Questionnaire_tilt_online_portal.zip](https://github.com/user-attachments/files/16909035/Climate_Action_Questionnaire_tilt_online_portal.zip)

This file is uploaded here so that it's download link can be used on the webtool app.
