### ISSUE TITLE
Add theme and layout

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltWebTool#21]
@AnneSchoenauer you may want to explore what's here: https://rstudio.github.io/bslib/index.html#get-started

Other useful links

* Dashoboard examples: https://rstudio.github.io/shinydashboard/examples.html
* General shiny gallery: https://shiny.posit.co/r/gallery/

**Comment by AnneSchoenauer** [comment]
Hi @maurolepore, 
Thanks a lot for these resources! I had a look at it and read a bit. With regard to 

1. Layout - colouring and font size

I found on this website here: https://rstudio.github.io/bslib/index.html#get-started - the link "theme". When clicking on it you get here: https://rstudio.github.io/bslib/articles/theming/index.html. If you then click on "see here for a hosted version" you get here: https://bslib.shinyapps.io/themer-demo/. As I understand there is the option to add a "Theme customiser". In the demo I was able to change the Font size, the kind of Font and also the colouring. I made a screenshot here: 

<img width="953" alt="image" src="https://github.com/2DegreesInvesting/tiltWebTool/assets/115623567/9abdc523-5e01-44c3-9dd0-b28ea641e640">
And also the fonts: 

<img width="980" alt="image" src="https://github.com/2DegreesInvesting/tiltWebTool/assets/115623567/d6b1b836-b8de-4a7f-b4a1-d5849e231ca1">. 

So maybe the easiest option is that to install this real-time theming [here](https://rstudio.github.io/bslib/articles/theming/index.html#real-time). 


2. Layout -  Components
If you look at the Theme demo, I think it all contains the components that we would need: 
- on the top being able to spring from one tab to another
- Plots
- Tables
- Upload buttons
I think we don't need a dashboard but maybe a landing page would be nice so that you can click from the landing page to the tabs on the top. 

I hope this already helps! But happy to discuss further when I am back from my holidays!

**Comment by maurolepore** [comment]
Awesome! Thanks!
